travis:
  secure:
    BINSTAR_TOKEN: sYXIID3Dj0xamx2yl7QVBkcxNICT1JvI88mYEIP46RWr+IUXmN86n2S4LVmd5ZU+kc+3VyEZxE7dNt/OFS6puZO8wbfXdelwPe8Q+jULhG/3FCcBuduuFwZNVo6c045pfhGteTN1Ij+1K3LMmg5lQpTC+eCTsS8+d+cyRBn1+W622xS1u32chaZWnjBn3hpMJ/eIfxpSOlAiEKOwOy38L6yuBQ06n30PCLDxDm+MrtE2osniIf8++INpT7ij9e2SGx7Y6kY2hlzvctfvnu8jPbn8BYZ0MCKYIIvFj2GpiKdDKnTlT8q4DHxqpsjcFtGemBmIcgkmUpX8KodfLtmwdt2ypGz+mR82hacbV58WkgHW/5LBuTOuhKW4ehy2u1l0GvQB/0JygafycFyCiWQhHOjLE6iZCfpz+KLt6ZvxJahZl3SDE9wxG3nb1pz3NrNg7LMMCDiksj+k4o+/yEWdT2Z2IoUUB/wQaQN7Z1WF+4MoMvru7ZvSm3OraL5F5Gp2IWgmAImyK7L3k0bjeMPPyxnjBRrhQLI70XP7lySVUqeSnUbTKGxaveHVG7M0Shz5PGRcqmkyvIVIvT27U5gwKX3Xcwqk7m75CARyXnpp/qlTA6e+GWJeCBd1FgpgZRJLMsxSxRO6NFpr/5aDgVLxRen3kHnlbPGHBhs3PFHdY1M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
